version: '3'

services:
  php:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - './app:/app'
      
  apache:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
    ports:
      - "8080:80"